# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  events: #触发器
    - timer: #签到
        parameters:
          name: beansign
          cronExpression: "0 1 0 * * * *"
          enable: true
          argument: jd_bean_sign
    - timer: #摇京豆 #京东汽车兑换 #interCenter渠道店铺签到
        parameters:
          name: clublottery_carexchange
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_club_lottery&jd_car_exchange&jd_monk_inter_shop_sign
    - timer: #东东农场 #东东萌宠 #口袋书店 #京喜农场 #京东极速版签到 #京东极速版红包 #美丽研究院
        parameters:
          name: fruit_pet_bookshop_jxnc_jxnc2_speedsign_speedredpocke_beauty
          cronExpression: "0 5 6-18/6,8 * * * *"
          enable: true
          argument: jd_fruit&jd_pet&jd_bookshop&jd_jxnc&jd_jxnc2&jd_speed_sign&jd_speed_redpocke&jd_beauty
    - timer: #宠汪汪喂食 #宠汪汪 #摇钱树 #京东种豆得豆 #京喜工厂 #东东工厂 #健康社区收取能量
        parameters:
          name: feedPets_joy_moneyTree_plantBean_dreamFactory_jdfactory_healthenergy
          cronExpression: "0 3 */1 * * * *"
          enable: true
          argument: jd_joy_feedPets&jd_joy&jd_moneyTree&jd_plantBean&jd_dreamFactory&jd_jdfactory&jd_z_health_energy
    - timer: #宠汪汪积分兑换京豆 #签到领现金 #点点券 #东东小窝 #京喜财富岛 #京东直播
        parameters:
          name: joyreward_cash_necklace_smallhome_cfd_live
          cronExpression: "0 6 0-16/8,20 * * * *"
          enable: true
          argument: jd_joy_reward&jd_cfd&jd_cash&jd_necklace&jd_small_home&jd_live
    - timer: #京东全民开红包 #进店领豆 #取关京东店铺商品 #京东抽奖机 #京东汽车 #京东秒秒币 #天天提鹅 #领金贴
        parameters:
          name: redPacket_shop_unsubscribe_lotteryMachine_car_ms_jintie
          cronExpression: "0 10 0 * * * *"
          enable: true
          argument: jd_redPacket&jd_shop&jd_unsubscribe&jd_lotteryMachine&jd_car&jd_ms&jd_jin_tie
    - timer: #天天提鹅 #5G超级盲盒 #健康社区
        parameters:
          name: dailyegg_mohe_healthcommunity
          cronExpression: "0 8 */3 * * * *"
          enable: true
          argument: jd_daily_egg&jd_mohe&jd_z_health_community
    - timer: #东东超市
        parameters:
          name: superMarket
          cronExpression: "0 15 */6 * * * *"
          enable: true
          argument: jd_superMarket
    - timer: #京豆变动通知 #疯狂的joy #京东排行榜 #领京豆额外奖励 #闪购盲盒 #京小兑 #超级无线组队分京豆
        parameters:
          name: beanchange_crazyjoy_rankingList_beanhome_sgmh_jxd
          cronExpression: "0 30 7 * * * *"
          enable: true
          argument: jd_bean_change&jd_crazy_joy&jd_rankingList&jd_bean_home&jd_sgmh&jd_jxd&jd_z_shop_captain
    - timer: #金融养猪 #十元街 #京东快递 #京东赚赚 #京喜签到 #女装盲盒 #关注有礼
        parameters:
          name: pigPet_syj_kd_jdzz_sign_nzmh_follow
          cronExpression: "0 20 0 * * * *"
          enable: true
          argument: jd_pigPet&jd_syj&jd_kd&jd_jdzz&jx_sign&jd_nzmh&jd_monk_shop_follow_sku
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
